---
title: "Final Project Data 205"
author: "Tiffany King"
date: "11/18/2021"
output: html_document
---

# Loading Libraries
```{r}
library('rvest')
library(tidyverse)
library(psych)
library(readr)
library(dplyr)
library(lubridate)
library(ggplot2)
library(plotly)
library(plyr)
library(highcharter)
library(RColorBrewer)
```
# Setting working directory
```{r}
setwd("/Users/tiffanyking/Desktop/DATA 205/DATA205/DATA205")
```

```{r}
WKridership<- read_csv("2019 Ridership weekday average.csv")
crimes<-read_csv("crime.csv")
``` 
# Examine the data
```{r}
str(WKridership)
head(WKridership)
```
## create dataframe from CSV
```{r}
year<- c("2010","2011","2012","2013","2014","2015","2016","2017","2018","2019","2020","2021")
averider<- c(705563,737313,721225,706591,693705,675077,621079,613665,605910,626269,176602,125557)
dailyentriesride<-data.frame(year,averider)
print(dailyentriesride)
```
# Barplot Average Daily Entries 
```{r}
options(scipen = 999)
ggplot(data=dailyentriesride, aes(x=year, y=averider)) +
  geom_bar(stat="identity", fill="red")+
  geom_text(aes(label=averider), vjust=1.6, color="white", size=3.5)+
   xlab("Year") +
  ylab("Passengers") +
  ggtitle("Average Daily Entries By Train") +
  ylim(0,800000)
  theme_minimal()
```

## Getting the WMATA Data
```{r}
library(tidyverse)
library(pdftools)
library(httr)
```

```{r}
get_wmata_data <- function(pdflink) {
  wmata_data <- pdf_text(pdflink) %>%
    str_split("\n")
  
  df = ""
  
  for (i in 1:length(wmata_data)) {
   
    for (line in wmata_data[[i]][9:(length(wmata_data[[i]])-2)]) {
      if (line == "" | is.na(line))
      {
        next
      } else {
        line <- str_squish(line)
        
        if (substr(line,21,27) %in% c("SUMMONS"))
        {
          stub <- str_split_fixed(line, " - ", 2)
          state <- substr(stub[1], nchar(stub[1])-1, nchar(stub[1]))
          stub_1 <- substr(stub[1],1, nchar(stub[1])-3)
          stub_2 <- stub[2]
          line <- paste(stub_1, stub_2, "\n")
          line <- paste(substr(line, 1, 36), state, " ", substr(line, 37, nchar(line)))
          prev_line <- line
          #print(line)
        }
        
        if (substr(line,21,27) %in% c("ARREST ", "REPORT "))
        {
          line <- paste(substr(line,1,26), "        ", substr(line,27,nchar(line)))
          stub <- str_split_fixed(line, " - ", 2)
          state <- substr(stub[1], nchar(stub[1])-1, nchar(stub[1]))
          stub_1 <- substr(stub[1],1, nchar(stub[1])-3)
          stub_2 <- stub[2]
          line <- paste(stub_1, stub_2, "\n")
          line <- paste(substr(line, 1, 36), state, " ", substr(line, 37, nchar(line)))
          prev_line <- line
          #print(line)
        }
        
        if (substr(line,3,3) !="/")
        {
          offense_stub <- str_split_fixed(line, " - ", 2)
          
          if (offense_stub[2]  != "")
          {
            line <- paste(stub_1, substr(line,6,nchar(line)))
            line <- paste(substr(line, 1, 36), state, " ", substr(line, 37, nchar(line)), "\n")
          }else{
            df <- substr(df, 1, nchar(df)-nchar(prev_line))
            line <- paste(substr(prev_line,1,nchar(prev_line)-2), offense_stub[1], "\n")
          }
        }
        
        df <- paste(df, line)
        print(line)
      }
    }
  }
  return(read_fwf(df, 
                  col_types=cols('c','c','c','c','c'),
                  fwf_cols(date=12, time=9, type=17, state=4, desc=NA)))
}
#fwf_cols(date=12, time=9, type=17, state=4, desc=NA),
# Now define what the links to the pdf files should look like and create a
# way to iterate through them to get multiple files at one go.

url <- "https://www.wmata.com/about/transit-police/upload/Monthly-Blotter-"
time_periods <- c("October-2021","September-2021", "August-2021", "July-2021", "June-2021","May-2021","April-2021","March-2021","February-2021","January-2021","December-2020","November-2020","October-2020","September-2020","August-2020","May-2020","April-2020","March-2020","February-2020","January-2020","December-2019","November-2019","October-2019","June-2019","November-2018")

 
url_exception_june_2020<-"https://www.wmata.com/about/transit-police/upload/June-2020-Blotter-Report.pdf"
df_exception_June_2020 <- get_wmata_data(url_exception_june_2020)

url_exception_july_2020<-"https://www.wmata.com/about/transit-police/upload/July-2020-Blotter.pdf"
df_exception_July_2020 <- get_wmata_data(url_exception_july_2020)

url_exception_july_2019<-"https://www.wmata.com/about/transit-police/upload/July-2019-Blotter.pdf"
df_exception_July_2019 <- get_wmata_data(url_exception_July_2019)

url_exception_may_2019<-"https://www.wmata.com/about/transit-police/upload/May-2019-Blotter-Report.pdf"
df_exception_May_2019 <- get_wmata_data(url_exception_May_2019)

url_exception_april_2019<-"https://www.wmata.com/about/transit-police/upload/Blotter-Report-April-2019.pdf"
df_exception_April_2019 <- get_wmata_data(url_exception_April_2019)

url_exception_march_2019<-"https://www.wmata.com/about/transit-police/upload/2019-March-Blotter-Report.pdf"
df_exception_March_2019 <- get_wmata_data(url_exception_March_2019)

url_exception_february_2019<-"https://www.wmata.com/about/transit-police/upload/February-2019-Monthly-Blotter-Report.pdf"
df_exception_February_2019 <- get_wmata_data(url_exception_February_2019)

url_exception_january_2019<-"https://www.wmata.com/about/transit-police/upload/January-2019-Monthly-Blotter-Report.pdf"
df_exception_January_2019 <- get_wmata_data(url_exception_January_2019)

url_exception_december_2018<-"https://www.wmata.com/about/transit-police/upload/Monthly-Blotter-2018-December.pdf"
df_exception_December_2018 <- get_wmata_data(url_exception_December_2018)

url_exception_october_2018<-"https://www.wmata.com/about/transit-police/upload/October-2018-Monthly-Crime-Blotter.pdf"
df_exception_October_2018 <- get_wmata_data(url_exception_October_2018)

url_exception_september_2018<-"https://www.wmata.com/about/transit-police/upload/September-2018-Blotter.pdf"
df_exception_September_2018 <- get_wmata_data(url_exception_September_2018)

url_exception_august_2018<-"https://www.wmata.com/about/transit-police/upload/August-2018-Monthly-Blotter.pdf"
df_exception_August_2018 <- get_wmata_data(url_exception_August_2018)

df_prev = ""

for (time_period in time_periods) {
  pdflink <- paste0(url, time_period, ".pdf")
  df_curr <- get_wmata_data(pdflink)

  if (df_prev == "")
  {
    df_prev <- df_curr
    df_wmata <- df_prev
  } else {
    df_wmata <- bind_rows(df_wmata, df_curr,url_exception_june_2020,url_exception_june_2020,url_exception_march_2019,url_exception_february_2019,url_exception_january_2019,url_exception_december_2018,url_exception_october_2018,url_exception_september_2018,url_exception_august_2018)
  }
}

# Check to make sure the data starts with start month and ends with end month.
df_wmata
tail(df_wmata)

```


```{r}

```

## Clean the WMATA data with NA's
```{r}

```

# Create Groupby Year & State (test)
```{r}
df_state<- df_wmata %>%
group_by(year) %>%
select(DC,MD,VA)
summarize(sum = sum(state), count = n()) %>%
arrange(year, state)

df_state
```

# Create Plot on the Crimes Committed by State
```{r}

```
# Creat a Groupby type & count (tester)
```{r}
df_wmata %>%                         # Count rows by group
  group_by(type) %>% 
  summarize(n = n())
```

```{r}
df_type <-df_wmata
  group_by(type)
df_type
```

```{r}
df_type<- df_wmata %>%
 group_by(type) %>%
    summarize(count=n())

```

# Create Plot on Type of Crimes by Type
```{r}
ggplot(df_wmata, aes(x=type, fill=type )) + 
  geom_bar( ) +
  scale_fill_hue(c = 40) +
  theme(legend.position="none")
```

# Create Plot on 
```{r}

```


#Census Data 
```{r}
library(httr)
library(jsonlite)
library(tidyverse)

# Import json data from Census API
data <- GET("https://api.census.gov/data/2019/acs/acs1/?get=NAME,B01001_001E,B01002_001E,C22001_001E,B25064_001E&for=county:*&in=state:24")
data <- content(data, as="text")

# Load into a data frame
df <- fromJSON(data)
class(df)
head(df)

# Change to tibble
df <- as_tibble(df)
head(df)

# Make first row column header names
names(df) <- c(df[1,])
head(df)

# Keep all but first row (which had the column header names)
df <- df[-1,]
head(df)

# Rename columns as needed
names(df) <- c('NAME',
               'B01001_001E' = 'Population',
               'B01002_001E' = 'Median_Age',
               'C22001_001E' = 'Household_Poverty',
               'B25064_001E' = 'Median_Gross_Rent',
               'state',
               'county')
head(df)

```

